# -- build arguments
ARG OPENAPX_CONTAINERID="rcxservice-unknown"
ARG OPENAPX_IMAGEOS="ubuntu"
ARG OPENAPX_RVERTARGET="0.0.0"


# For now ... rely on latest ubuntu baseline OS
FROM openapx/rbin:latest-$OPENAPX_IMAGEOS-R$OPENAPX_RVERTARGET


# -- add license file to root directory
COPY -chmod=444 LICENSE /LICENSE-rcxservice


# -- configuration files
#    note: this is the input location for Shell scripts below
COPY --chmod=444 libs-$OPENAPX_IMAGEOS /opt/openapx/config/rcxservice/



# -- scripted sequence
#    1) add binary library dependencies
#    5) clean-up

#COPY --chmod=755 scripts/rcxservice/build_r.sh /scripts/rcxservice/
RUN /opt/openapx/utilities/container-id.sh && \
    /opt/openapx/utilities/bin-libs.sh /opt/openapx/config/rcxservice/libs-$OPENAPX_OSIMAGE && \
    rm -Rf /scripts

# /scripts/rbin/build_r.sh && \
# find /logs/R/rbin -type f -exec chmod u+r-wx,g+r-wx,o-rwx {} \; && \
# find /logs/R/rbin -type d -exec chmod u+rx-w,g+rx-w,o-rwx {} \; && \

