# -- build arguments
ARG OPENAPX_IMAGEOS="ubuntu"
ARG OPENAPX_RVERTARGET="0.0.0"

# For now ... rely on latest ubuntu baseline OS
FROM openapx/rbin:latest-${OPENAPX_IMAGEOS}-R${OPENAPX_RVERTARGET}


# -- build arguments
ARG OPENAPX_CONTAINERID="rcxservice-unknown"

# -- re-declare build args under FROM
ARG OPENAPX_IMAGEOS="ubuntu"
ARG OPENAPX_RVERTARGET="0.0.0"



# -- add license file to root directory
COPY --chmod=444 LICENSE /LICENSE-rcxservice


# -- configuration files
#    note: this is the input location for Shell scripts below

COPY --chmod=444 libs-${OPENAPX_IMAGEOS} /opt/openapx/config/rcxservice/



# -- scripted sequence
#    1) add binary library dependencies
#    5) clean-up

COPY --chmod=755 .scripts/deploy-* /scripts/rcxservice/
RUN /opt/openapx/utilities/container-id.sh && \
    /opt/openapx/utilities/bin-libs.sh /opt/openapx/config/rcxservice/libs-${OPENAPX_IMAGEOS} && \
    /scripts/rcxservice/deploy-rcxservice.sh && \
    /scripts/rcxservice/deploy-nginx-proxy.sh && \
    rm -Rf /scripts


# -- app entrypoint 

# - expose standard port for HTTPS
EXPOSE 443

# - entrypoint script
COPY --chmod=755 scripts/entrypoint.sh /
ENTRYPOINT /entrypoint.sh
